
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn package -DskipTests

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/cloud-slang/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-c1aa4727096926c3f2b896e0637666f1215555a8
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            