
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile assembly:single

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/cloud-slang/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-27fe74e519b9472efab156cc53a995b42559f3e2
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            