
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn package -DskipTests

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/cloud-slang/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-2633fbf962e948ff042aaefaeea3026e98903048
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            